import { Product } from "@/types";

export const PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Relax Chamomile",
        slug: "relax-chamomile",
        tagline: "Gentle chamomile for a restful evening.",
        description: "Salam Tea Leaves’ Relax Chamomile is made from whole chamomile flowers sourced from small farms. Our careful drying preserves the delicate floral aroma and clean, honey-like finish. Perfect as an evening ritual, this caffeine-free brew is gentle on the stomach and beautifully aromatic.",
        price: 850,
        image_url: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-001",
        ingredients: "Chamomile flowers (100%)",
        brewing_instructions: "95–100°C, steep 5–7 min",
        benefits: "May help promote relaxation and a sense of calm.",
        warning: "Not recommended for people allergic to plants in the Asteraceae family. Consult physician if pregnant."
    },
    {
        id: "2",
        name: "Detox Mint",
        slug: "detox-mint",
        tagline: "Bright, cooling mint for digestion and freshness.",
        description: "Our Detox Mint blends fresh peppermint leaves with cooling spearmint for an uplifting cup. Lightly herbaceous with a clean finish, this caffeine-free blend is ideal after meals or whenever you need a palate-refresh.",
        price: 450,
        image_url: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-002",
        ingredients: "Peppermint (Mentha × piperita), Spearmint (Mentha spicata)",
        brewing_instructions: "95°C, steep 3–5 min",
        benefits: "May help soothe occasional digestive discomfort.",
        warning: "Avoid if you have GERD/acid reflux sensitivity to mint."
    },
    {
        id: "3",
        name: "Energy Ginger Green",
        slug: "energy-ginger-green",
        tagline: "Energizing green tea with ginger kick.",
        description: "Energy Ginger Green combines high-quality green tea leaves with sun-dried ginger and bright lemon peel. The result is a bright, slightly spicy cup with natural antioxidants and a refreshing finish.",
        price: 600,
        image_url: "/energy-ginger-green.jpg",
        category: "Green Tea",
        stock: 50,
        sku: "SL-003",
        ingredients: "Green tea, dried ginger root, lemon peel",
        brewing_instructions: "75–80°C, steep 2–3 min",
        benefits: "May help increase alertness and provide a gentle warming sensation.",
        warning: "Contains caffeine; not recommended for pregnant women or children without medical advice."
    },
    {
        id: "4",
        name: "Hibiscus Chill",
        slug: "hibiscus-chill",
        tagline: "Tart hibiscus for a vibrant, cool cup.",
        description: "Our Hibiscus Chill is made from premium hibiscus calyces delivering a refreshing, tangy cup. Serve iced for a natural, colorful refresher or hot with a hint of honey.",
        price: 550,
        image_url: "https://images.unsplash.com/photo-1563911892437-1feda9d5c2c5?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-004",
        ingredients: "Hibiscus, rosehip",
        brewing_instructions: "95–100°C, steep 4–6 min",
        benefits: "A refreshing, antioxidant-rich herbal infusion.",
        warning: "May interact with certain medications; check with a healthcare provider if taking prescriptions."
    },
    {
        id: "5",
        name: "Immunity Turmeric & Lemon",
        slug: "immunity-turmeric-lemon",
        tagline: "Turmeric root and bright lemon for everyday support.",
        description: "Immunity Turmeric & Lemon combines ground turmeric with pepper and zesty lemon peel for a warming, comforting tea. Black pepper enhances turmeric’s natural compounds for a fuller flavor.",
        price: 950,
        image_url: "https://images.unsplash.com/photo-1615485925763-867862f850a0?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-005",
        ingredients: "Turmeric root, black pepper, lemon peel",
        brewing_instructions: "95–100°C, steep 5–7 min",
        benefits: "May support general well-being.",
        warning: "Not recommended during pregnancy without medical advice."
    },
    {
        id: "6",
        name: "Rooibos Vanilla",
        slug: "rooibos-vanilla",
        tagline: "Naturally sweet rooibos with a creamy vanilla finish.",
        description: "Our Rooibos Vanilla pairs South African rooibos with a natural vanilla profile for a rich and soothing cup. Naturally caffeine-free and low-tannin, it’s an excellent afternoon option.",
        price: 650,
        image_url: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-006",
        ingredients: "Rooibos, natural vanilla flavoring",
        brewing_instructions: "95–100°C, steep 4–6 min",
        benefits: "A comforting caffeine-free alternative to black tea.",
        warning: "None typical; check flavoring source for allergies."
    },
    {
        id: "7",
        name: "Lavender Sleep",
        slug: "lavender-sleep",
        tagline: "Soothing lavender for restful evenings.",
        description: "Lavender Sleep brings together delicate lavender flowers with calming lemon balm to create a fragrant, soothing evening infusion. The floral aroma helps create a calming routine before bed.",
        price: 900,
        image_url: "https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-007",
        ingredients: "Lavender buds, lemon balm",
        brewing_instructions: "95–100°C, steep 5–7 min",
        benefits: "May help promote relaxation.",
        warning: "Not recommended if allergic to lavender."
    },
    {
        id: "8",
        name: "Lemongrass Digestive",
        slug: "lemongrass-digestive",
        tagline: "Zesty lemongrass for a light, uplifting cup.",
        description: "Our Lemongrass Digestive is made from hand-cut lemongrass stalks for a bright, citrusy cup that’s light and refreshing. Naturally caffeine-free, it’s ideal after meals.",
        price: 450,
        image_url: "https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&q=80&w=800",
        category: "Herbal",
        stock: 50,
        sku: "SL-008",
        ingredients: "Lemongrass (Cymbopogon citratus)",
        brewing_instructions: "95–100°C, steep 5–7 min",
        benefits: "A refreshing, palate-cleansing herbal infusion.",
        warning: "None typical; consult your physician if pregnant."
    },
    {
        id: "9",
        name: "Masala Chai",
        slug: "masala-chai",
        tagline: "Robust black tea with warming spices.",
        description: "Salam Tea Leaves’ Masala Chai is a bold blend designed to be brewed strong and enjoyed with milk and sweetener. Our black tea base is balanced with warming spices like cardamom, cinnamon, and ginger.",
        price: 350,
        image_url: "https://images.unsplash.com/photo-1564890369478-c5af469fb013?auto=format&fit=crop&q=80&w=800",
        category: "Black Tea",
        stock: 50,
        sku: "SL-009",
        ingredients: "Black tea, cardamom, cinnamon, ginger, cloves",
        brewing_instructions: "95–100°C, steep 3–4 min",
        benefits: "A warming, aromatic morning or afternoon choice.",
        warning: "Contains caffeine."
    },
    {
        id: "10",
        name: "Organic Earl Grey",
        slug: "organic-earl-grey",
        tagline: "Classic Earl Grey with bergamot uplift.",
        description: "Our Organic Earl Grey is crafted from a single-origin black tea base scented with high-quality bergamot for the classic floral-citrus aroma. Smooth, bright, and elegant.",
        price: 800,
        image_url: "https://images.unsplash.com/photo-1563822249510-17288da76c8c?auto=format&fit=crop&q=80&w=800",
        category: "Black Tea",
        stock: 50,
        sku: "SL-010",
        ingredients: "Organic black tea, bergamot oil",
        brewing_instructions: "95°C, steep 3–4 min",
        benefits: "A classic aromatic tea for daily enjoyment.",
        warning: "Contains caffeine. Check bergamot allergy if relevant."
    }
];
