-- Seed Data for Products
INSERT INTO public.products (
        name,
        slug,
        tagline,
        description,
        price,
        image_url,
        category,
        stock,
        sku,
        ingredients,
        brewing_instructions,
        benefits,
        warning
    )
VALUES (
        'Relax Chamomile',
        'relax-chamomile',
        'Gentle chamomile for a restful evening.',
        'Salam Tea Leaves’ Relax Chamomile is made from whole chamomile flowers sourced from small farms. Our careful drying preserves the delicate floral aroma and clean, honey-like finish. Perfect as an evening ritual, this caffeine-free brew is gentle on the stomach and beautifully aromatic.',
        5.50,
        'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-001',
        'Chamomile flowers (100%)',
        '95–100°C, steep 5–7 min',
        'May help promote relaxation and a sense of calm.',
        'Not recommended for people allergic to plants in the Asteraceae family. Consult physician if pregnant.'
    ),
    (
        'Detox Mint',
        'detox-mint',
        'Bright, cooling mint for digestion and freshness.',
        'Our Detox Mint blends fresh peppermint leaves with cooling spearmint for an uplifting cup. Lightly herbaceous with a clean finish, this caffeine-free blend is ideal after meals or whenever you need a palate-refresh.',
        4.80,
        'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-002',
        'Peppermint (Mentha × piperita), Spearmint (Mentha spicata)',
        '95°C, steep 3–5 min',
        'May help soothe occasional digestive discomfort.',
        'Avoid if you have GERD/acid reflux sensitivity to mint.'
    ),
    (
        'Energy Ginger Green',
        'energy-ginger-green',
        'Energizing green tea with ginger kick.',
        'Energy Ginger Green combines high-quality green tea leaves with sun-dried ginger and bright lemon peel. The result is a bright, slightly spicy cup with natural antioxidants and a refreshing finish.',
        6.50,
        'https://images.unsplash.com/photo-1594631252845-a28d5789f251?auto=format&fit=crop&q=80&w=800',
        'Green Tea',
        50,
        'SL-003',
        'Green tea, dried ginger root, lemon peel',
        '75–80°C, steep 2–3 min',
        'May help increase alertness and provide a gentle warming sensation.',
        'Contains caffeine; not recommended for pregnant women or children without medical advice.'
    ),
    (
        'Hibiscus Chill',
        'hibiscus-chill',
        'Tart hibiscus for a vibrant, cool cup.',
        'Our Hibiscus Chill is made from premium hibiscus calyces delivering a refreshing, tangy cup. Serve iced for a natural, colorful refresher or hot with a hint of honey.',
        5.20,
        'https://images.unsplash.com/photo-1563911892437-1feda9d5c2c5?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-004',
        'Hibiscus, rosehip',
        '95–100°C, steep 4–6 min',
        'A refreshing, antioxidant-rich herbal infusion.',
        'May interact with certain medications; check with a healthcare provider if taking prescriptions.'
    ),
    (
        'Immunity Turmeric & Lemon',
        'immunity-turmeric-lemon',
        'Turmeric root and bright lemon for everyday support.',
        'Immunity Turmeric & Lemon combines ground turmeric with pepper and zesty lemon peel for a warming, comforting tea. Black pepper enhances turmeric’s natural compounds for a fuller flavor.',
        7.00,
        'https://images.unsplash.com/photo-1615485925763-867862f850a0?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-005',
        'Turmeric root, black pepper, lemon peel',
        '95–100°C, steep 5–7 min',
        'May support general well-being.',
        'Not recommended during pregnancy without medical advice.'
    ),
    (
        'Rooibos Vanilla',
        'rooibos-vanilla',
        'Naturally sweet rooibos with a creamy vanilla finish.',
        'Our Rooibos Vanilla pairs South African rooibos with a natural vanilla profile for a rich and soothing cup. Naturally caffeine-free and low-tannin, it’s an excellent afternoon option.',
        6.00,
        'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-006',
        'Rooibos, natural vanilla flavoring',
        '95–100°C, steep 4–6 min',
        'A comforting caffeine-free alternative to black tea.',
        'None typical; check flavoring source for allergies.'
    ),
    (
        'Lavender Sleep',
        'lavender-sleep',
        'Soothing lavender for restful evenings.',
        'Lavender Sleep brings together delicate lavender flowers with calming lemon balm to create a fragrant, soothing evening infusion. The floral aroma helps create a calming routine before bed.',
        5.80,
        'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-007',
        'Lavender buds, lemon balm',
        '95–100°C, steep 5–7 min',
        'May help promote relaxation.',
        'Not recommended if allergic to lavender.'
    ),
    (
        'Lemongrass Digestive',
        'lemongrass-digestive',
        'Zesty lemongrass for a light, uplifting cup.',
        'Our Lemongrass Digestive is made from hand-cut lemongrass stalks for a bright, citrusy cup that’s light and refreshing. Naturally caffeine-free, it’s ideal after meals.',
        4.90,
        'https://images.unsplash.com/photo-1595981267035-7b04ca84a82d?auto=format&fit=crop&q=80&w=800',
        'Herbal',
        50,
        'SL-008',
        'Lemongrass (Cymbopogon citratus)',
        '95–100°C, steep 5–7 min',
        'A refreshing, palate-cleansing herbal infusion.',
        'None typical; consult your physician if pregnant.'
    ),
    (
        'Masala Chai',
        'masala-chai',
        'Robust black tea with warming spices.',
        'Salam Tea Leaves’ Masala Chai is a bold blend designed to be brewed strong and enjoyed with milk and sweetener. Our black tea base is balanced with warming spices like cardamom, cinnamon, and ginger.',
        5.20,
        'https://images.unsplash.com/photo-1564890369478-c5af469fb013?auto=format&fit=crop&q=80&w=800',
        'Black Tea',
        50,
        'SL-009',
        'Black tea, cardamom, cinnamon, ginger, cloves',
        '95–100°C, steep 3–4 min',
        'A warming, aromatic morning or afternoon choice.',
        'Contains caffeine.'
    ),
    (
        'Organic Earl Grey',
        'organic-earl-grey',
        'Classic Earl Grey with bergamot uplift.',
        'Our Organic Earl Grey is crafted from a single-origin black tea base scented with high-quality bergamot for the classic floral-citrus aroma. Smooth, bright, and elegant.',
        6.40,
        'https://images.unsplash.com/photo-1563822249510-17288da76c8c?auto=format&fit=crop&q=80&w=800',
        'Black Tea',
        50,
        'SL-010',
        'Organic black tea, bergamot oil',
        '95°C, steep 3–4 min',
        'A classic aromatic tea for daily enjoyment.',
        'Contains caffeine. Check bergamot allergy if relevant.'
    );