-- Create the subscribers table
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Turn on Row Level Security
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
-- Allow anyone to insert (since it's a public form), but only admins to read
create policy "Public can insert subscribers" on subscribers for
insert with check (true);
create policy "Admins can view subscribers" on subscribers for
select using (auth.role() = 'service_role');